apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deployer-role
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources:
      - pods
      - pods/log
      - deployments
      - replicasets
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - pods/exec
      - pods/attach
    verbs:
      - create
      - get
      - update
  - apiGroups: ["networking.k8s.io", "extensions"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
