---
cluster:
  name: applications-cluster

destinations:
  - name: otlp-gateway
    type: otlp
    url: http://otlp-gateway.example.com
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: false}  # Disable traces in other destinations as all traces should be sent to the tail-sampler

  - name: tail-sampler
    type: otlp
    url: tail-sampler-deployment.default.svc.cluster.local:4317  # Update if using a different namespace or deployment name
    protocol: grpc
    tls:
      insecure: true
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}

applicationObservability:
  enabled: true
  receivers:
    otlp:
      http:
        enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
