apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "heart-attack-risk-prediction-change-name"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure relevant resources are cleaned up
spec:
  project: default
  sources:
    - repoURL: "https://github.com/dtuan2604/heart-attack-risk-prediction.git"
      path: "helm-charts/hara"
      targetRevision: "main"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "model-serving"
  syncPolicy:
    automated: # Single source of truth for existing applications in Kubernetes
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
