apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "heart-attack-risk-prediction-application"
  namespace: {{ $.Values.global.argoResourceNamespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure relevant resources are cleaned up
spec:
  project: default
  sources:
    - repoURL: {{ $.Values.global.repoURL | quote }}
      path: "helm-charts/hara"
      targetRevision: {{ $.Values.global.targetRevision | quote }}
  destination:
    server: {{ $.Values.global.destinationServer | quote }}
    namespace: {{ $.Values.global.argoResourceNamespace | quote }}
  syncPolicy:
    automated: # Single source of truth for existing applications in Kubernetes
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
