apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nginx-ingress-controller"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure relevant resources are cleaned up
spec:
  project: default
  source:
    repoURL: "https://github.com/dtuan2604/heart-attack-risk-prediction.git"
    path: "helm-charts/nginx-ingress"
    targetRevision: "main"
    helm:
      values: |
        fullnameOverride: nginx-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "nginx-system"
  syncPolicy:
    automated: # Single source of truth for existing applications in Kubernetes
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
