global:
  repoURL: "https://github.com/dtuan2604/heart-attack-risk-prediction.git"
  targetRevision: "main"
  destinationServer: "https://kubernetes.default.svc"
  clusterResourcePath: "deployment/cluster-resources"
  argoResourceNamespace: "argocd"
