services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-jenkins:latest
    container_name: jenkins
    privileged: true
    ports:
      - 8081:8080
      - 50000:50000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    env_file:
      - ../.env
volumes:
  jenkins_home:
