services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: tysonhoang/custom-jenkins:latest
    container_name: jenkins
    privileged: true
    ports:
      - 8081:8080
      - 50000:50000
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env
volumes:
  jenkins_home:
