apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: {{ $.Values.global.argoResourceNamespace | quote }}
spec:
  project: default
  source:
    repoURL: {{ $.Values.global.repoURL | quote }}
    targetRevision: {{ $.Values.global.targetRevision | quote }}
    path: {{ $.Values.global.clusterResourcePath | quote }}  # points to the folder with all child app YAMLs
  destination:
    server: {{ $.Values.global.destinationServer | quote }}
    namespace: {{ $.Values.global.argoResourceNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
